### ISSUE TITLE
Spotify client not detected

### ISSUE THREAD

**Issue by vipau** [pywkm/ulauncher-spotify#8]
I'm running a very minimal system.  
I'd assume this requires something that I don't have installed, if that's the case, please update the README :)

Running ulauncher and spotify (with working dbus in place):
```
2019-05-15 12:27:24,106 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 173, in on_input_key_press_event
    self.enter_result_item()
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 298, in enter_result_item
    if not self.results_nav.enter(self._get_user_query(), index, alt=alt):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/ItemNavigation.py", line 58, in enter
    action.run()
  File "/usr/lib/python2.7/site-packages/ulauncher/api/shared/action/LaunchAppAction.py", line 25, in run
    logger.info('Run application %s (%s)' % (force_unicode(app.get_name()), self.filename))
AttributeError: 'NoneType' object has no attribute 'get_name'
```

**Comment by pywkm** [comment]
Hi, thanks for reporting.

Few questions:
1. Is this something that worked a few weeks ago, but stopped after a recent update (I made few changes in May) or you just installed the plugin recently and don't know if it's a regression or not?
2. I understand that when Spotify client is running and you open Ulauncher window, type "`sp<space>`" in it you still get the message "Run Spotify desktop app first"?
3. When Spotify client isn't running and you open Ulauncher, type "`spo`" there - is Spotify listed on apps to launch - I mean in the list provided by core Ulauncher functionality? If so, does launching it from this list work?

**Comment by vipau** [comment]
Ok sorry. Reported too early... It was actually a dbus problem, fixed by launching with dbus-launch.
Sorry again for reporting mistakenly! You may delete this issue.

**Comment by pywkm** [comment]
No problem. :)
